name: Docker Image skillsync CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t my-image:latest -f skillsync/Dockerfile skillsync/
    - name: Clean up Docker resources
      run: docker system prune -f
