name: PyBuilder Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Navigate to project directory
        run: cd skillsync
        
      - name: Create Virtual Environment
        if: matrix.os == 'ubuntu-latest'
        run: python -m venv venv

      - name: Activate and Set PYTHONPATH
        if: matrix.os == 'ubuntu-latest'
        run: |
          source venv/bin/activate
          export PYTHONPATH=$PYTHONPATH:/skillsync
      
      - name: Ensure correct permissions
        run: chmod +x skillsync/build.py
        
      - name: Install PyBuilder
        run: pip install pybuilder

      - name: Run PyBuilder tests
        run: pyb run_unit_tests
